my_string="eMobilis"
my_int=67
my_float=453.8988
my_complex=1j
my_bool=True
my_bol2=False
my_list=["hp","lenovo","Dell","IBM"]
my_tuple=("mangoes","pineapples","oranges","lemons")
my_set={"Nissan","Toyota","Mercedes","Subaru"}
my_dictionary={"name":"Michelle","age":22}\

print(type(my_string))
print(type(my_int))
print(type(my_float))
print(type(my_complex))
print(type(my_bool))
print(type(my_bol2))
print(type(my_list))
print(type(my_tuple))
print(type(my_set))
print(type(my_dictionary))
